########################## 
# Define basic settings #
#########################

executor:           lsf
scheduler:          greedy
jobs:               500
latency-wait:       5
rerun-incomplete:   false
use-singularity:    true
use-conda:          true
retries:            1

#############################
# Define default resources #
############################

default-resources:
  mem_mb: 95000
  queue: "express"
  project: "acc_PVI"
  runtime: "12h"
  span: "\"span[hosts=1]\""
