samples: "samples.csv"
reference_genome: "/sc/arion/work/khaliz03/opt/vRAPID/db/sars-cov-2/reference.fasta"
genbank: "/sc/arion/work/khaliz03/opt/vRAPID/db/sars-cov-2/COVID.gbk"
reverse_primer: "/sc/arion/work/khaliz03/opt/vRAPID/db/sars-cov-2/SARS-CoV-2_primers_3prime_NI.fa"
forward_primer: "/sc/arion/work/khaliz03/opt/vRAPID/db/sars-cov-2/SARS-CoV-2_primers_5prime_NI.fa"
virus: "SARS-CoV-2"
path: "/sc/arion/projects/PVI/genomes/assembly/TD006962/SARS-CoV-2/VS"
length: "29903"
ref_fasta_headers: "BA.2.86"
assembly_pipeline: "vRAPID"
kingdom: "Viruses"
primer_file: "/sc/arion/work/khaliz03/opt/vRAPID/db/sars-cov-2/primer_file.tsv"
kraken_db: "/sc/arion/projects/FluVac/kraken2_standard_db_2024/" 
qualimap_input: "multibamqc_input.txt"
run_id: "test_run"
