samples: "samples.csv"
project: "PVI"
reference: "scov/229E/229E.fasta"
genbank: "scov/229E/229E.gbk"
reverse_primer: "scov/229E/229E_primers_3prime_NI.fa"
forward_primer: "scov/229E/229E_primers_5prime_NI.fa"
primer_set_2kb: "scov/229E/229E_2kb.primer.csv"
primer_set_1_5kb: "scov/229E/229E_1.5kb.primer.csv"
virus: "sCoV"
path: "/hpc/users/khaliz03/scratch/TD006247"
length: "27317"
ref_fasta_headers: "229E"
