samples: "samples.csv"
run_id: "TD006471"
reference: "sars-cov-2/COVID.fa"
genbank: "sars-cov-2/COVID.gbk"
reverse_primer: "sars-cov-2/SARS-CoV-2_primers_3prime_NI.fa"
forward_primer: "sars-cov-2/SARS-CoV-2_primers_5prime_NI.fa"
primer_set_2kb: "sars-cov-2/SARS-CoV-2_primers_2kb_set.tsv"
primer_set_1_5kb: "sars-cov-2/SARS-CoV-2_primers_1.5kb_set.tsv"
virus: "SARS-CoV-2"
path: "/sc/arion/projects/PVI/pipeline_testing/TD006471/SARS-CoV-2/VS/"
length: "29903"
ref_fasta_headers: "MN908947"
