samples: "samples.csv"
project: "PVI"
reference: "sars-cov-2/COVID.fa"
genbank: "sars-cov-2/COVID.gbk"
reverse_primer: "sars-cov-2/SARS-CoV-2_primers_3prime_NI.fa"
forward_primer: "sars-cov-2/SARS-CoV-2_primers_5prime_NI.fa"
primer_set_2kb: "sars-cov-2/SARS-CoV-2_primers_2kb_set.tsv"
primer_set_1_5kb: "sars-cov-2/SARS-CoV-2_primers_1.5kb_set.tsv"
virus: "SARS-CoV-2"
path: "/sc/arion/projects/PVI/genomes/assembly/TD006650/SARS-CoV-2/AG"
length: "29903"
ref_fasta_headers: "MN908947"
assembly_pipeline: "vRAPID"
